# Generated by Django 5.2.5 on 2025-08-15 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyMarketUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('etat', models.CharField(default='fermée', max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='nbr_caisse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('montant_session', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('caisse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EasyMarketUsers.caisse')),
                ('caissier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
